apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5LmNuLWJlaWppbmcuYWxpeXVuY3MuY29tIjp7InVzZXJuYW1lIjoi6aOf6IGU572R56eR5oqAIiwicGFzc3dvcmQiOiJhbHBoZXNoMTIzIUAiLCJlbWFpbCI6IiIsImF1dGgiOiI2YU9mNklHVTU3MlI1NmVSNW9xQU9tRnNjR2hsYzJneE1qTWhRQT09In19fQ==
kind: Secret
metadata:
  name: registry-aliyun
  namespace: mysql
type: kubernetes.io/dockerconfigjson